# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  - override /algorithm: sac_mod

n_epochs: 60

env: 'FetchReach-v1'

algorithm:
  replay_buffer_class: HerReplayBuffer
  buffer_size: 1000000
  batch_size: 256
  policy_kwargs:
    net_arch:
      - 256
      - 256
      - 256
  replay_buffer_kwargs:
    n_sampled_goal: 4
    goal_selection_strategy: 'future'
    online_sampling: True

hydra:
  sweeper:
    study_name: sac_mod_FetchReach
    max_trials: 2
    n_jobs: 3
    direction: maximize
    max_duration_minutes: 6000
    min_trials_per_param: 2
    max_trials_per_param: 3
    search_space:
      ++algorithm.critic_select:
        type: categorical
        choices:
          - min
          - max

