# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  - override /algorithm: cleansac

env: 'FetchPush-v2'

#############################################################################
## Parameters determined through hyperopt with search space lr, gamma, tau ##
#############################################################################
#algorithm:
#  name: 'cleansac'
#  learning_rate: 0.00023
#  ent_coef: auto
#  buffer_size: 1_000_000
#  learning_starts: 100
#  batch_size: 256
#  gamma: 0.915
#  tau: 0.078
#  use_her: True
#  n_critics: 1

############################################################################################################
## Parameters as in SB3 Zoo (https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/her.yml) ##
############################################################################################################
algorithm:
  name: 'cleansac'
  learning_rate: !!float 1e-3
  ent_coef: auto
  buffer_size: 1_000_000
  learning_starts: 100
  batch_size: 2048
  gamma: 0.95
  tau: 0.05
  use_her: True
  n_critics: 2

performance_testing_conditions:
  # In 2 out of 3 tests, the eval/success rate should be at least 0.7 after 20k steps.

  total_runs: 3 # How many runs in total:

  succ_runs: 2 # This number of runs should meet the conditions:

  eval_columns: eval/success_rate # This is what we evaluate to determine success. Will use this to override the \'early_stop_data_column\' parameter of main.yaml

  eval_value: 0.7 # This is the value we determine for success. Will use this to determine and override the \'early_stop_threshold\' parameter of main.yaml

  max_steps: 500_000 # This is the time limit for checking the success. Will use this and the \'eval_after_n_steps\' parameter of main.yaml to determine the n_epochs parameter in main.yaml.

hydra:
  sweeper:
    n_jobs: 3
    _target_: hydra_plugins.hydra_custom_optuna_sweeper.performance_testing_sweeper.PerformanceTestingSweeper
    study_name: cleansac_her_FetchPush-test
