# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  - override /algorithm: sac

n_epochs: 100

env: 'FetchPush-v1'

algorithm:
  replay_buffer_class: HerReplayBuffer
  buffer_size: 1000000
  batch_size: 256
  policy_kwargs:
    net_arch:
      - 256
      - 256
      - 256
  replay_buffer_kwargs:
    n_sampled_goal: 4
    goal_selection_strategy: 'future'
    online_sampling: True

hydra:
  sweeper:
    study_name: sac_her_FetchPush
    max_trials: 32
    n_jobs: 8
    direction: maximize
    max_duration_minutes: 18000
    min_trials_per_param: 2
    max_trials_per_param: 3
    search_space:
      ++algorithm.learning_rate:
        type: float
        low: 0.0001
        high: 0.005
        log: true
      ++algorithm.gamma:
        type: float
        low: 0.9
        high: 0.99
        log: true
      ++algorithm.tau:
        type: float
        low: 0.005
        high: 0.1
        log: true
      ++algorithm.policy_kwargs.n_critics:
        type: int
        low: 1
        high: 4
