# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  - override /algorithm: sac

env: 'Ant4Rooms-v1'

algorithm:
  replay_buffer_class: HerReplayBuffer
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.0018
  gamma: 0.98
  tau: 0.07
  policy_kwargs:
    n_critics: 2
    net_arch:
      - 256
      - 256
      - 256
  replay_buffer_kwargs:
    n_sampled_goal: 4
    goal_selection_strategy: 'future'
    online_sampling: True

performance_testing_conditions:
  # In 2 out of 8 tests, the test/success rate should be at least 0.65 after 500k steps.

  total_runs: 8 # How many runs in total:

  succ_runs: 2 # This number of runs should meet the conditions:

  eval_columns: test/success_rate # This is what we evaluate to determine success. Will use this to override the \'early_stop_data_column\' parameter of main.yaml

  eval_value: 0.65 # This is the value we determine for success. Will use this to determine and override the \'early_stop_threshold\' parameter of main.yaml

  # ca. 6 hours with GPU
  max_steps: 500_000 # This is the time limit for checking the success. Will use this and the \'eval_after_n_steps\' parameter of main.yaml to determine the n_epochs parameter in main.yaml.

hydra:
  sweeper:
    n_jobs: 8
    _target_: hydra_plugins.hydra_custom_optuna_sweeper.performance_testing_sweeper.PerformanceTestingSweeper
    study_name: sac_her_Ant4Rooms-test
