# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  - override /algorithm: basic

env: 'Reach1DOF-v0'
env_kwargs:
  reward_type: 'dense'

algorithm:
  learning_rate: 0.001
  net_arch: [16,16]
  noise_factor: 0.1

wandb: 0

performance_testing_conditions:
  # In 1 out of 5 tests, the eval/success rate should be at least 0.8 after 60K steps.

  total_runs: 5 # How many runs in total:

  succ_runs: 1 # This number of runs should meet the conditions:

  eval_columns: eval/success_rate # This is what we evaluate to determine success. Will use this to override the \'early_stop_data_column\' parameter of main.yaml

  eval_value: 0.8 # This is the value we determine for success. Will use this to determine and override the \'early_stop_threshold\' parameter of main.yaml

  max_steps: 60000 # This is the time limit for checking the success. Will use this and the \'eval_after_n_steps\' parameter of main.yaml to determine the n_epochs parameter in main.yaml.

hydra:
  sweeper:
    n_jobs: 5
    _target_: hydra_plugins.hydra_custom_optuna_sweeper.performance_testing_sweeper.PerformanceTestingSweeper
    study_name: basic_Reach1DOF-test
