# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.

# Scilab-RL quality control:
# Test validated.
# Testing date: 13.11.2023
# Branch: devel-testing
# Commit: fc9bac1e9070be904de22e42b1ebf76a65e6586e


defaults:
  - override /algorithm: sac

env: 'Blocks-o0-gripper_random-v1'

# The number of training steps after which to evaluate the policy.
eval_after_n_steps: 2000

# The number of testing rollouts.
n_test_rollouts: 10

# The n last epochs over which to average for determining early stopping condition.
early_stop_last_n: 3

# The data column on which early stopping is based.
early_stop_data_column: 'eval/success_rate'

algorithm:
  replay_buffer_class: HerReplayBuffer
  buffer_size: 1000000
  batch_size: 256
  learning_rate: 0.001
  gamma: 0.95
  tau: 0.015
  policy_kwargs:
    n_critics: 2
    net_arch:
      - 256
      - 256
      - 256
  replay_buffer_kwargs:
    n_sampled_goal: 4
    goal_selection_strategy: 'future'

performance_testing_conditions:
  # In 2 out of 3 tests, the eval/success rate should be at least 0.9 after 10k steps.

  total_runs: 3 # How many runs in total:

  succ_runs: 2 # This number of runs should meet the conditions:

  eval_columns: eval/success_rate # This is what we evaluate to determine success. Will use this to override the \'early_stop_data_column\' parameter of main.yaml

  eval_value: 0.9 # This is the value we determine for success. Will use this to determine and override the \'early_stop_threshold\' parameter of main.yaml

  # ca. 10 minutes with GPU
  max_steps: 10_000 # This is the time limit for checking the success. Will use this and the \'eval_after_n_steps\' parameter of main.yaml to determine the n_epochs parameter in main.yaml.

hydra:
  sweeper:
    n_jobs: 3
    _target_: hydra_plugins.hydra_custom_optuna_sweeper.performance_testing_sweeper.PerformanceTestingSweeper
    study_name: sac_her_Blocks_o0_random-test
