# @package _global_
#############################################################
## The performance for this environment is still quite bad ##
## Maybe works better with single layer approach           ##
#############################################################

# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  # access algorithm config group to get the default parameters of hac
  - override /algorithm: sac

env: 'OOBlocks-o2-gripper_above-v1'

# The n last epochs over which to average for determining early stopping condition.
early_stop_last_n: 4

algorithm:
  learning_rate: 3e-4

hydra:
  sweeper:
    study_name: sac_OO-Blocks-o2-gripper_above-v1
    storage: sqlite:///sac_OO-Blocks-o2-gripper_above-v1.db
    max_trials: 1
    n_jobs: 1
    direction: maximize
    max_duration_minutes: 3000
    min_trials_per_param: 3
    max_trials_per_param: 6
    #search_space:
    #  algorithm.learning_rate:
    #    type: float
    #    low: 3e-4
    #    high: 3e-4
    #    step: 0

