# @package _global_
# Changes specified in this config should be interpreted as relative to the _global_ package.
defaults:
  # access algorithm config group to get the default parameters of her
  - override /algorithm: sac

# overwrite parameters of main.yaml
env: 'close_drawer-state-v0'

# use HER
algorithm:
  replay_buffer_class: HerReplayBuffer
  learning_rate: 0.00091
  replay_buffer_kwargs:
    n_sampled_goal: 2
    goal_selection_strategy: 'future'
    online_sampling: True

performance_testing_conditions:
  # In 1 out of 3 tests, the eval/success rate should be at least 0.3 after 100.000 steps.

  total_runs: 3 # How many runs in total:

  succ_runs: 1 # This number of runs should meet the conditions:

  eval_columns: eval/success_rate # This is what we evaluate to determine success. Will use this to override the \'early_stop_data_column\' parameter of main.yaml

  eval_value: 0.3 # This is the value we determine for success. Will use this to determine and override the \'early_stop_threshold\' parameter of main.yaml

  max_steps: 100000 # This is the time limit for checking the success. Will use this and the \'eval_after_n_steps\' parameter of main.yaml to determine the n_epochs parameter in main.yaml.

hydra:
  sweeper:
    n_jobs: 3
    _target_: hydra_plugins.hydra_custom_optuna_sweeper.performance_testing_sweeper.PerformanceTestingSweeper
    study_name: sac_her-close_drawer-state-v0-test
